# Importation des packages

In [4]:
import tensorflow as tf
import pandas as pd
import numpy as np
from keras.utils import to_categorical
#import matplotlib.pyplot as plt

import math
from glob import glob

# Syncrhonisation avec Google Drive

In [5]:
#from google.colab import drive
#drive.mount('/content/gdrive/', force_remount=True)

# Importation des données

# Chargement des données sauvegardées

## First line

In [9]:
#PATH_DATA = 'gdrive/MyDrive/AIForYou/Datasets/supervisée/classification/non_structurée/Tetris/first_line/'
PATH_DATA = 'data/first_line/'

In [10]:
training_data_first_line = pd.read_csv(f'{PATH_DATA}train_data-first_line.csv')
training_data_first_line.shape

(112577, 4)

In [11]:
testing_data_first_line = pd.read_csv(f'{PATH_DATA}test_data-first_line.csv')
testing_data_first_line.shape

(1119, 4)

In [12]:
training_data_images_first_line = np.load(f'{PATH_DATA}train_data_images-first_line.npy')
training_data_images_first_line.shape

(112577, 20, 10, 1)

In [13]:
testing_data_images_first_line = np.load(f'{PATH_DATA}test_data_images-first_line.npy')
testing_data_images_first_line.shape

(1119, 20, 10, 1)

## ten lines

In [16]:
#PATH_DATA = 'gdrive/MyDrive/AIForYou/Datasets/supervisée/classification/non_structurée/Tetris/ten_lines/'
PATH_DATA = 'data/ten_lines/'

In [17]:
training_data_ten_lines = pd.read_csv(f'{PATH_DATA}train_data-beginning_game.csv')
training_data_ten_lines.shape

(160528, 4)

In [18]:
testing_data_ten_lines = pd.read_csv(f'{PATH_DATA}test_data-beginning_game.csv')
testing_data_ten_lines.shape

(656, 4)

In [19]:
training_data_images_ten_lines = np.load(f'{PATH_DATA}train_data_images-beginning_game.npy')
training_data_images_ten_lines.shape

(160528, 20, 10, 1)

In [20]:
testing_data_images_ten_lines = np.load(f'{PATH_DATA}test_data_images-beginning_game.npy')
testing_data_images_ten_lines.shape

(656, 20, 10, 1)

## Complete game

In [21]:
#PATH_DATA = 'gdrive/MyDrive/AIForYou/Datasets/supervisée/classification/non_structurée/Tetris/complete_game/'
PATH_DATA = 'data/complete_game/'

In [22]:
training_data_complete_game = pd.read_csv(f'{PATH_DATA}train_data-complete_game.csv')
training_data_complete_game.shape

(212506, 4)

In [23]:
testing_data_complete_game = pd.read_csv(f'{PATH_DATA}test_data-complete_game.csv')
testing_data_complete_game.shape

(12916, 4)

In [25]:
training_data_images_complete_game = np.load(f'{PATH_DATA}train_data_images-complete_game.npy')
training_data_images_complete_game.shape

(212506, 20, 10, 1)

In [26]:
testing_data_images_complete_game = np.load(f'{PATH_DATA}test_data_images-complete_game.npy')
testing_data_images_complete_game.shape

(12916, 20, 10, 1)

## Finale dataframe

In [30]:
#PATH_DATA = 'gdrive/MyDrive/AIForYou/Datasets/supervisée/classification/non_structurée/Tetris/final_dataframe/'
PATH_DATA = 'data/final_dataframe/'

In [31]:
training_data_final_dataframe = pd.read_csv(f'{PATH_DATA}train_data-final_dataframe.csv')
training_data_final_dataframe.shape

(65563, 4)

In [32]:
testing_data_final_dataframe = pd.read_csv(f'{PATH_DATA}test_data-final_dataframe.csv')
testing_data_final_dataframe.shape

(2517, 4)

In [33]:
training_data_images_final_dataframe = np.load(f'{PATH_DATA}train_data_images-final_dataframe.npy')
training_data_images_final_dataframe.shape

(65563, 20, 10, 1)

In [34]:
testing_data_images_final_dataframe = np.load(f'{PATH_DATA}test_data_images-final_dataframe.npy')
testing_data_images_final_dataframe.shape

(2517, 20, 10, 1)

## Concat data

In [66]:
training_data = pd.concat([training_data_first_line,
                           training_data_ten_lines,
                           training_data_complete_game,
                           training_data_final_dataframe])
training_data.shape

(551174, 4)

In [67]:
testing_data = pd.concat([testing_data_first_line,
                           testing_data_ten_lines,
                           testing_data_complete_game,
                          testing_data_final_dataframe])
testing_data.shape

(17208, 4)

In [68]:
training_data_images = np.concatenate([training_data_images_first_line,
                                       training_data_images_ten_lines,
                                       training_data_images_complete_game,
                                       training_data_images_final_dataframe])
training_data_images.shape

(551174, 20, 10, 1)

In [69]:
testing_data_images = np.concatenate([testing_data_images_first_line,
                                       testing_data_images_ten_lines,
                                       testing_data_images_complete_game,
                                      testing_data_images_final_dataframe])
testing_data_images.shape

(17208, 20, 10, 1)

# Mettre les labels au bon format

In [70]:
def output_form(data):
    column = data.pop('column')
    column = list(map(lambda x : int(x), column))
    column = to_categorical(column)
    column = np.array(column)
    rotation = data.pop('rotation')
    rotation = list(map(lambda x : int(x), rotation))
    rotation = to_categorical(rotation)
    rotation = np.array(rotation)
    return (rotation, column)

In [71]:
y_train = output_form(training_data.loc[:, ['column', 'rotation']])

In [72]:
new_train = np.zeros([training_data.shape[0], 40])
cmpt = 0
for rot, col in zip(y_train[0], y_train[1]):

  new_train[cmpt, :] = np.dot(rot.T.reshape(-1, 1), col.reshape(1, -1)).flatten()
  cmpt += 1

In [73]:
np.sum(new_train, axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

In [74]:
y_test = output_form(testing_data.loc[:, ['column', 'rotation']])

In [75]:
new_test = np.zeros([testing_data.shape[0], 40])
cmpt = 0
for rot, col in zip(y_test[0], y_test[1]):

  new_test[cmpt, :] = np.dot(rot.T.reshape(-1, 1), col.reshape(1, -1)).flatten()
  cmpt += 1

In [76]:
np.sum(new_test, axis=1)

array([1., 1., 1., ..., 1., 1., 1.])

# Distribution des données

In [77]:

np.sum(new_train, axis=0)

array([37804., 20069., 25927., 26111., 25978., 25155., 26028., 24510.,
       12914.,     0., 48608., 13826., 19778., 17507., 17929., 17754.,
       18349., 15952., 24402., 11912.,  9799.,  5214.,  6635.,  6467.,
        6467.,  6612.,  5142.,  9848.,    75.,     0.,  6496.,  4771.,
        5405.,  5201.,  5160.,  5143.,  6133.,  4349., 21604.,   140.])

# Création des générateurs

In [78]:
class image_generator():

    # Class is a dataset wrapper for better training performance
    def __init__(self, image_list, target_list, norm=False, batch_size=8, shuffle=True, data_aug=True, no_whole=False):
        self.image_list = image_list
        self.target_list = target_list
        self.id_list = np.arange(image_list.shape[0])
        self.batch_size = batch_size
        self.len = math.ceil(len(self.image_list) / self.batch_size)
        self.idx = 0
        self.shuffle = shuffle
        self.norm = norm
        self.no_whole = no_whole
        self.data_aug = data_aug
        if self.shuffle :
            np.random.shuffle(self.id_list)

    def __norm__(self, batch):
        return np.array([ (x - np.min(x) )/ (np.max(x) - np.min(x)) for x in batch])

    def __getitem__(self):
        if (self.idx + 1) * self.batch_size > len(self.image_list) :
            idx_end = len(self.image_list)
        else :
            idx_end = (self.idx + 1) * self.batch_size


        id_list_batch = self.id_list[self.idx * self.batch_size:idx_end]
        batch_img = self.image_list[id_list_batch]

        if self.norm :
            batch_img = self.__norm__(batch_img)

        if self.data_aug:
            batch_img = np.array([self.data_augmentation(x)for x in batch_img])

        if self.no_whole:
            batch_img = np.array([self.no_whole(x)for x in batch_img])

        return batch_img

    def __gettarget__(self):
        if (self.idx + 1) * self.batch_size > len(self.image_list) :
            idx_end = len(self.image_list)
        else :
            idx_end = (self.idx + 1) * self.batch_size

        id_list_batch = self.id_list[self.idx * self.batch_size:idx_end]

        target_batch = self.target_list[id_list_batch]


        return target_batch



    def __getbatch__(self):
        batch = self.__getitem__()

        x = np.array(batch)
        y = self.__gettarget__()
        return x, y

    # Generate flow of data
    def loader(self):
        # load data from somwhere with Python, and yield them
        while True:
            batch_input, batch_output = self.__getbatch__()
            self.__iter__()
            yield (batch_input, batch_output)

    def __iter__(self):
        if self.idx + 2 > self.len :
            self.idx = 0
            if self.shuffle :
                np.random.shuffle(self.id_list)
        else :
            self.idx += 1

    def get_len(self):
        return self.len

    def get_minimum_maximum_height(self, game_matrix):
        lines, columns, _ = game_matrix.shape
        minimum_height = np.inf
        maximum_height = -np.inf
        for column in np.arange(columns):
          for line in np.arange(2,lines):
            if game_matrix[line, column, 0] == 1 :

              if lines-line < minimum_height:
                minimum_height = lines-line
              if lines-line > maximum_height:
                maximum_height = lines-line
              break

        if minimum_height == np.inf or maximum_height==-np.inf:
          maximum_height = 0
          minimum_height = 0
        return maximum_height, minimum_height

    def increase_row(self, game_matrix, maximum_height):

      number_row = np.random.randint(18-maximum_height+1)

      new_game_matrix = np.zeros(game_matrix.shape)

      new_game_matrix[:2, :, :] = game_matrix[:2, :, :]

      new_game_matrix[20-maximum_height-number_row:20-number_row, :, :] = game_matrix[20-maximum_height:, :, :]

      new_game_matrix[20-number_row:, :, :] = 1

      return new_game_matrix

    def reduce_row(self, game_matrix, minimum_height, maximum_height):

      number_row = np.random.randint(minimum_height+1)

      new_game_matrix = np.zeros(game_matrix.shape)

      new_game_matrix[:2, :, :] = game_matrix[:2, :, :]

      new_game_matrix[-((maximum_height-number_row)):, :, :] = game_matrix[20-maximum_height:20-number_row, :, :]

      return new_game_matrix


    def data_augmentation(self, game_matrix):

      maximum_height, minimum_height = self.get_minimum_maximum_height(game_matrix)


      add_row = np.random.randint(2)

      if add_row and maximum_height<18 :
        game_matrix = self.increase_row(game_matrix, maximum_height)


      elif not(add_row) and minimum_height>0 and maximum_height>minimum_height:

        game_matrix = self.reduce_row(game_matrix, minimum_height, maximum_height)
        maximum_height, minimum_height = self.get_minimum_maximum_height(game_matrix)


      return game_matrix

    def no_whole(self, game_matrix):

      gamme_matrix_without_current_tetromino = game_matrix.copy()

      width, colmun, _ = gamme_matrix_without_current_tetromino.shape

      for col in np.arange(colmun):
        first_tetromino = np.argmax(gamme_matrix_without_current_tetromino[2:, col, :])

        gamme_matrix_without_current_tetromino[first_tetromino:, col, :]=1

      return gamme_matrix_without_current_tetromino



In [79]:
train_datagen = image_generator(training_data_images, new_train, batch_size=512, norm=False, data_aug=True, no_whole=False, shuffle=True)
test_datagen = image_generator(testing_data_images, new_test, batch_size=512, norm=False, data_aug=False, no_whole=False, shuffle=True)

In [107]:
train_datagen = tf.data.Dataset.from_tensor_slices((training_data_images, new_train)).batch(512)
test_datagen = tf.data.Dataset.from_tensor_slices((testing_data_images, new_test)).batch(512)

In [109]:
for i in range(5):
  x, y = next(iter(train_datagen.take(2)))
  print(x[0, :, :, 0])
  print(x.shape)
  print(y.shape)

tf.Tensor(
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(20, 10), dtype=float64)
(512, 20, 10, 1)
(512, 40)
tf.Tensor(
[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0

# Initialisation du modèle

In [81]:
def base_model(inputs):
  x = tf.keras.layers.ZeroPadding2D(padding=(2, 2))(inputs)
  x = tf.keras.layers.Conv2D(32, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.Conv2D(32, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.AveragePooling2D((2, 2))(x)
  #x = tf.keras.layers.Dropout(0.1)(x)
  x = tf.keras.layers.Conv2D(64, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.Conv2D(64, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.AveragePooling2D((2, 2))(x)
  #x = tf.keras.layers.Dropout(0.1)(x)
  x = tf.keras.layers.Conv2D(128, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.Conv2D(128, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.AveragePooling2D((2, 2))(x)
  x = tf.keras.layers.Conv2D(256, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.Conv2D(256, (3, 3), padding="same", activation='relu')(x)
  x = tf.keras.layers.Flatten()(x)
  x = tf.keras.layers.Dropout(0.1)(x)
  x = tf.keras.layers.Dense(512, activation='relu')(x)
  x = tf.keras.layers.Dropout(0.1)(x)
  x = tf.keras.layers.Dense(256, activation='relu')(x)
  x = tf.keras.layers.Dropout(0.1)(x)
  x = tf.keras.layers.Dense(128, activation='relu')(x)
  x = tf.keras.layers.Dropout(0.1)(x)
  output = tf.keras.layers.Dense(units = '40', activation = 'softmax')(x)
  model = tf.keras.models.Model(inputs=inputs, outputs = output)

  return model

In [82]:
inputs = tf.keras.layers.Input(shape=(20, 10, 1))

In [83]:
model = base_model(inputs)

In [84]:

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
             loss = tf.keras.losses.CategoricalCrossentropy(),
             metrics=[tf.keras.metrics.AUC(multi_label=True),
                      tf.keras.metrics.CategoricalAccuracy()])

In [85]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 20, 10, 1)]       0         
                                                                 
 zero_padding2d_1 (ZeroPadd  (None, 24, 14, 1)         0         
 ing2D)                                                          
                                                                 
 conv2d_8 (Conv2D)           (None, 24, 14, 32)        320       
                                                                 
 conv2d_9 (Conv2D)           (None, 24, 14, 32)        9248      
                                                                 
 average_pooling2d_3 (Avera  (None, 12, 7, 32)         0         
 gePooling2D)                                                    
                                                                 
 conv2d_10 (Conv2D)          (None, 12, 7, 64)         1849

# Entraînement du moèle

In [86]:
#PATH_model = 'gdrive/MyDrive/AIForYou/applications/tetris/training_model/checkpoint_epoch-{epoch}_val_loss-{val_loss:.4f}.hdf5'
PATH_model = 'training_model/checkpoint_epoch-{epoch}_val_loss-{val_loss:.4f}.hdf5'

In [87]:
callback = tf.keras.callbacks.ModelCheckpoint(PATH_model, monitor="val_loss", mode="min", save_best_only=True)

In [88]:
model.load_weights('training_model/checkpoint_epoch-109_val_loss-0.8788.hdf5')

In [89]:
#from sklearn.utils import class_weight
#class_weight = class_weight.compute_class_weight(class_weight='balanced',
#                                               classes=np.unique(np.argmax(new_train, axis=1)),
#                                               y= np.argmax(new_train, axis=1))

In [90]:
#class_weight = dict(zip(np.unique(np.argmax(new_train, axis=1)), class_weight))
#class_weight[9] = 0
#class_weight[29] = 0

In [91]:
def scheduler(epoch, lr):
  if epoch < 100 :
    return lr
  elif epoch == 100 :
    return lr * 0.1
  else :
    return lr * np.power(0.99,(epoch / 1000))

In [92]:
#train_datagen = image_generator(training_data_images, new_train, batch_size=512, norm=False, data_aug=False, no_whole=False, shuffle=True)
#test_datagen = image_generator(testing_data_images, new_test, batch_size=512, norm=False, data_aug=False, no_whole=False, shuffle=True)

In [93]:
#history = model.fit(train_datagen.loader(),
#                    batch_size=train_datagen.batch_size,
#                    steps_per_epoch= train_datagen.get_len(),
#                    initial_epoch=0,
#                    epochs=30,
#                    validation_data=test_datagen.loader(),
#                    validation_steps=test_datagen.get_len(),
#                    validation_batch_size=test_datagen.batch_size,
#                    callbacks=[callback, tf.keras.callbacks.LearningRateScheduler(scheduler)])

In [127]:
train_datagen = tf.data.Dataset.from_tensor_slices((training_data_images, new_train)).batch(512)
test_datagen = tf.data.Dataset.from_tensor_slices((testing_data_images, new_test)).batch(512)

In [128]:
history = model.fit(train_datagen,
                    initial_epoch=109,
                    epochs=1000,
                    validation_data=test_datagen,
                    callbacks=[callback, tf.keras.callbacks.LearningRateScheduler(scheduler)])

Epoch 110/1000
   8/1077 [..............................] - ETA: 5:55 - loss: 0.8660 - auc_1: 0.8868 - categorical_accuracy: 0.6438

KeyboardInterrupt: 

In [129]:
train_datagen = image_generator(training_data_images, new_train, batch_size=512, norm=False, data_aug=True, no_whole=False, shuffle=True)
test_datagen = image_generator(testing_data_images, new_test, batch_size=512, norm=False, data_aug=False, no_whole=False, shuffle=True)

In [130]:
history = model.fit(train_datagen.loader(),
                    batch_size=train_datagen.batch_size,
                    steps_per_epoch= train_datagen.get_len(),
                    initial_epoch=123,
                    epochs=1000,
                    validation_data=test_datagen.loader(),
                    validation_steps=test_datagen.get_len(),
                    validation_batch_size=test_datagen.batch_size,
                    callbacks=[callback, tf.keras.callbacks.LearningRateScheduler(scheduler)])

Epoch 124/1000
1077/1077 [==============================] - 401s 372ms/step - loss: 0.9097 - auc_1: 0.9192 - categorical_accuracy: 0.6730 - val_loss: 0.9038 - val_auc_1: 0.8898 - val_categorical_accuracy: 0.6989 - lr: 9.7274e-04
Epoch 125/1000
1077/1077 [==============================] - 412s 382ms/step - loss: 0.9013 - auc_1: 0.9210 - categorical_accuracy: 0.6750 - val_loss: 0.9017 - val_auc_1: 0.8901 - val_categorical_accuracy: 0.7010 - lr: 9.7153e-04
Epoch 126/1000
1077/1077 [==============================] - 397s 369ms/step - loss: 0.8984 - auc_1: 0.9204 - categorical_accuracy: 0.6750 - val_loss: 0.9091 - val_auc_1: 0.8886 - val_categorical_accuracy: 0.7014 - lr: 9.7031e-04
Epoch 127/1000
1077/1077 [==============================] - 393s 365ms/step - loss: 0.8975 - auc_1: 0.9200 - categorical_accuracy: 0.6754 - val_loss: 0.9089 - val_auc_1: 0.8891 - val_categorical_accuracy: 0.7044 - lr: 9.6908e-04
Epoch 128/1000
1077/1077 [==============================] - 420s 390ms/step - loss: 

KeyboardInterrupt: 

In [ ]:
model.save_weights('training_model/checkpoint_epoch-123_val_loss-0.9010.hdf5')

In [ ]:
pred_test = model.predict(testing_data_images)

In [ ]:
import seaborn as sns
from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(np.argmax(new_test, axis=1), np.argmax(pred_test, axis=1), normalize='true')

In [ ]:
sns.heatmap(cf_matrix, annot=False, fmt=".2f", cmap='Blues')
plt.show()

In [ ]:
np.max(cf_matrix, axis=0)

In [ ]:
model.save_weights('gdrive/MyDrive/AIForYou/applications/tetris/training_model/checkpoint_epoch-14_val_loss-1.0322.hdf5')

In [ ]:
matrix = np.array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [ ]:
matrix.shape

In [ ]:
x, y = next(train_datagen.loader())

In [ ]:
x[1, :, :, 0]

In [ ]:
y

In [ ]:
model.predict()